# Generated by Django 4.0.5 on 2022-06-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(verbose_name='any text')),
                ('Created_date', models.DateTimeField(verbose_name='date created')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
